### PR TITLE
Add Themed Icon

### LINKED ISSUE #321: Themed Icon (Android 13)
Please consider adding support for Themed Icons in Android 13.
See https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add_your_adaptive_icon_to_your_app

Search keywords: Themed Icons, Material You, monochrome, app icon.

### PR DESCRIPTION
**Pull request by thgoebel**
Fixes #321.

Tested on Android 13 (classic + Themed) and Android 10 (classic only, no regression).

### CODE REVIEW

**Comment by tom-anders** [comment]
Cool, thanks! Will try to have a look at it tomorrow and create a new release

**Comment by tom-anders** [comment]
Thanks!

**Comment by tom-anders** [comment]
By the way, if you want to get further involved in helping develop the app, just let me know :)

**Comment by thgoebel** [comment]
I can't commit to much unfortunately. These days I'm jumping around between projects a lot, mostly scratching my own itches :grimacing: 

Would you mind tagging a new release, so that F-Droid's bot can pick it up? Thanks!

**Pull request merged**
